
import { Classe, Eleve, Cours } from "./types";

export const classes: Classe[] = [
  { id: "1", nom: "6ème A", niveau: "6ème", effectif: 24 },
  { id: "2", nom: "5ème B", niveau: "5ème", effectif: 28 },
  { id: "3", nom: "4ème C", niveau: "4ème", effectif: 26 },
  { id: "4", nom: "3ème D", niveau: "3ème", effectif: 30 },
  { id: "5", nom: "2nde A", niveau: "2nde", effectif: 32 },
  { id: "6", nom: "1ère B", niveau: "1ère", effectif: 30 },
  { id: "7", nom: "Terminale C", niveau: "Terminale", effectif: 28 },
];

export const eleves: Eleve[] = [
    // 6ème A (24 élèves)
    { id: "1", nom: "Dupont", prenom: "Jean", classeId: "1", photo: "/avatars/1.jpg" },
    { id: "2", nom: "Martin", prenom: "Sophie", classeId: "1", photo: "/avatars/2.jpg" },
    { id: "3", nom: "Dubois", prenom: "Lucas", classeId: "1", photo: "/avatars/3.jpg" },
    { id: "4", nom: "Lefebvre", prenom: "Emma", classeId: "1", photo: "/avatars/4.jpg" },
    { id: "18", nom: "Morel", prenom: "Hugo", classeId: "1", photo: "/avatars/18.jpg" },
    { id: "19", nom: "Girard", prenom: "Léa", classeId: "1", photo: "/avatars/19.jpg" },
    { id: "20", nom: "Bonnet", prenom: "Thomas", classeId: "1", photo: "/avatars/20.jpg" },
    { id: "21", nom: "Roux", prenom: "Camille", classeId: "1", photo: "/avatars/21.jpg" },
    { id: "22", nom: "Fontaine", prenom: "Maxime", classeId: "1", photo: "/avatars/22.jpg" },
    { id: "23", nom: "Blanc", prenom: "Manon", classeId: "1", photo: "/avatars/23.jpg" },
    { id: "24", nom: "Perrot", prenom: "Enzo", classeId: "1", photo: "/avatars/24.jpg" },
    { id: "25", nom: "Chevalier", prenom: "Clara", classeId: "1", photo: "/avatars/25.jpg" },
    { id: "26", nom: "Francois", prenom: "Nathan", classeId: "1", photo: "/avatars/26.jpg" },
    { id: "27", nom: "Legrand", prenom: "Inès", classeId: "1", photo: "/avatars/27.jpg" },
    { id: "28", nom: "Gauthier", prenom: "Mathis", classeId: "1", photo: "/avatars/28.jpg" },
    { id: "29", nom: "Garnier", prenom: "Louise", classeId: "1", photo: "/avatars/29.jpg" },
    { id: "30", nom: "Muller", prenom: "Alexandre", classeId: "1", photo: "/avatars/30.jpg" },
    { id: "31", nom: "Boyer", prenom: "Chloé", classeId: "1", photo: "/avatars/31.jpg" },
    { id: "32", nom: "Schmitt", prenom: "Antoine", classeId: "1", photo: "/avatars/32.jpg" },
    { id: "33", nom: "Noël", prenom: "Juliette", classeId: "1", photo: "/avatars/33.jpg" },
    { id: "34", nom: "Leclerc", prenom: "Baptiste", classeId: "1", photo: "/avatars/34.jpg" },
    { id: "35", nom: "Barre", prenom: "Léna", classeId: "1", photo: "/avatars/35.jpg" },
    { id: "36", nom: "Perrier", prenom: "Raphaël", classeId: "1", photo: "/avatars/36.jpg" },
    { id: "37", nom: "Caron", prenom: "Zoé", classeId: "1", photo: "/avatars/37.jpg" },
  
    // 5ème B (28 élèves)
    { id: "5", nom: "Leroy", prenom: "Thomas", classeId: "2", photo: "/avatars/5.jpg" },
    { id: "6", nom: "Moreau", prenom: "Chloé", classeId: "2", photo: "/avatars/6.jpg" },
    { id: "7", nom: "Petit", prenom: "Nathan", classeId: "2", photo: "/avatars/7.jpg" },
    { id: "38", nom: "Bertrand", prenom: "Léa", classeId: "2", photo: "/avatars/38.jpg" },
    { id: "39", nom: "Rousseau", prenom: "Hugo", classeId: "2", photo: "/avatars/39.jpg" },
    { id: "40", nom: "Fournier", prenom: "Emma", classeId: "2", photo: "/avatars/40.jpg" },
    { id: "41", nom: "Masson", prenom: "Lucas", classeId: "2", photo: "/avatars/41.jpg" },
    { id: "42", nom: "Marchand", prenom: "Manon", classeId: "2", photo: "/avatars/42.jpg" },
    { id: "43", nom: "Dumont", prenom: "Maxime", classeId: "2", photo: "/avatars/43.jpg" },
    { id: "44", nom: "Denis", prenom: "Clara", classeId: "2", photo: "/avatars/44.jpg" },
    { id: "45", nom: "Lemaire", prenom: "Enzo", classeId: "2", photo: "/avatars/45.jpg" },
    { id: "46", nom: "Huet", prenom: "Inès", classeId: "2", photo: "/avatars/46.jpg" },
    { id: "47", nom: "Colin", prenom: "Mathis", classeId: "2", photo: "/avatars/47.jpg" },
    { id: "48", nom: "Vasseur", prenom: "Louise", classeId: "2", photo: "/avatars/48.jpg" },
    { id: "49", nom: "Poirier", prenom: "Alexandre", classeId: "2", photo: "/avatars/49.jpg" },
    { id: "50", nom: "Fernandez", prenom: "Chloé", classeId: "2", photo: "/avatars/50.jpg" },
    { id: "51", nom: "Mercier", prenom: "Antoine", classeId: "2", photo: "/avatars/51.jpg" },
    { id: "52", nom: "Berger", prenom: "Juliette", classeId: "2", photo: "/avatars/52.jpg" },
    { id: "53", nom: "Lecomte", prenom: "Baptiste", classeId: "2", photo: "/avatars/53.jpg" },
    { id: "54", nom: "Renard", prenom: "Léna", classeId: "2", photo: "/avatars/54.jpg" },
    { id: "55", nom: "Faure", prenom: "Raphaël", classeId: "2", photo: "/avatars/55.jpg" },
    { id: "56", nom: "Andre", prenom: "Zoé", classeId: "2", photo: "/avatars/56.jpg" },
    { id: "57", nom: "Cousin", prenom: "Paul", classeId: "2", photo: "/avatars/57.jpg" },
    { id: "58", nom: "Guillot", prenom: "Lola", classeId: "2", photo: "/avatars/58.jpg" },
    { id: "59", nom: "Bourgeois", prenom: "Arthur", classeId: "2", photo: "/avatars/59.jpg" },
    { id: "60", nom: "Pascal", prenom: "Sarah", classeId: "2", photo: "/avatars/60.jpg" },
    { id: "61", nom: "Didier", prenom: "Tom", classeId: "2", photo: "/avatars/61.jpg" },
    { id: "62", nom: "Gillet", prenom: "Maëlys", classeId: "2", photo: "/avatars/62.jpg" },
  
    // 4ème C (26 élèves)
    { id: "8", nom: "Roux", prenom: "Léa", classeId: "3", photo: "/avatars/8.jpg" },
    { id: "9", nom: "Simon", prenom: "Hugo", classeId: "3", photo: "/avatars/9.jpg" },
    { id: "63", nom: "Paris", prenom: "Emma", classeId: "3", photo: "/avatars/63.jpg" },
    { id: "64", nom: "Marty", prenom: "Lucas", classeId: "3", photo: "/avatars/64.jpg" },
    { id: "65", nom: "Aubry", prenom: "Manon", classeId: "3", photo: "/avatars/65.jpg" },
    { id: "66", nom: "Guyot", prenom: "Maxime", classeId: "3", photo: "/avatars/66.jpg" },
    { id: "67", nom: "Carre", prenom: "Clara", classeId: "3", photo: "/avatars/67.jpg" },
    { id: "68", nom: "Charles", prenom: "Enzo", classeId: "3", photo: "/avatars/68.jpg" },
    { id: "69", nom: "Renault", prenom: "Inès", classeId: "3", photo: "/avatars/69.jpg" },
    { id: "70", nom: "Charpentier", prenom: "Mathis", classeId: "3", photo: "/avatars/70.jpg" },
    { id: "71", nom: "Menard", prenom: "Louise", classeId: "3", photo: "/avatars/71.jpg" },
    { id: "72", nom: "Maillard", prenom: "Alexandre", classeId: "3", photo: "/avatars/72.jpg" },
    { id: "73", nom: "Baron", prenom: "Chloé", classeId: "3", photo: "/avatars/73.jpg" },
    { id: "74", nom: "Bertin", prenom: "Antoine", classeId: "3", photo: "/avatars/74.jpg" },
    { id: "75", nom: "Poulain", prenom: "Juliette", classeId: "3", photo: "/avatars/75.jpg" },
    { id: "76", nom: "Riviere", prenom: "Baptiste", classeId: "3", photo: "/avatars/76.jpg" },
    { id: "77", nom: "Philippe", prenom: "Léna", classeId: "3", photo: "/avatars/77.jpg" },
    { id: "78", nom: "Lacroix", prenom: "Raphaël", classeId: "3", photo: "/avatars/78.jpg" },
    { id: "79", nom: "Nguyen", prenom: "Zoé", classeId: "3", photo: "/avatars/79.jpg" },
    { id: "80", nom: "Jacob", prenom: "Paul", classeId: "3", photo: "/avatars/80.jpg" },
    { id: "81", nom: "Lebrun", prenom: "Lola", classeId: "3", photo: "/avatars/81.jpg" },
    { id: "82", nom: "Gilbert", prenom: "Arthur", classeId: "3", photo: "/avatars/82.jpg" },
    { id: "83", nom: "Levy", prenom: "Sarah", classeId: "3", photo: "/avatars/83.jpg" },
    { id: "84", nom: "Roche", prenom: "Tom", classeId: "3", photo: "/avatars/84.jpg" },
    { id: "85", nom: "Roy", prenom: "Maëlys", classeId: "3", photo: "/avatars/85.jpg" },
    { id: "86", nom: "Picard", prenom: "Noah", classeId: "3", photo: "/avatars/86.jpg" },
  
    // 3ème D (30 élèves)
    { id: "10", nom: "Michel", prenom: "Camille", classeId: "4", photo: "/avatars/10.jpg" },
    { id: "11", nom: "Bernard", prenom: "Alexandre", classeId: "4", photo: "/avatars/11.jpg" },
    { id: "87", nom: "Daniel", prenom: "Léa", classeId: "4", photo: "/avatars/87.jpg" },
    { id: "88", nom: "Fleury", prenom: "Hugo", classeId: "4", photo: "/avatars/88.jpg" },
    { id: "89", nom: "Adam", prenom: "Emma", classeId: "4", photo: "/avatars/89.jpg" },
    { id: "90", nom: "Raymond", prenom: "Lucas", classeId: "4", photo: "/avatars/90.jpg" },
    { id: "91", nom: "Rey", prenom: "Manon", classeId: "4", photo: "/avatars/91.jpg" },
    { id: "92", nom: "Benoit", prenom: "Maxime", classeId: "4", photo: "/avatars/92.jpg" },
    { id: "93", nom: "Langlois", prenom: "Clara", classeId: "4", photo: "/avatars/93.jpg" },
    { id: "94", nom: "Payet", prenom: "Enzo", classeId: "4", photo: "/avatars/94.jpg" },
    { id: "95", nom: "Perret", prenom: "Inès", classeId: "4", photo: "/avatars/95.jpg" },
    { id: "96", nom: "Barthelemy", prenom: "Mathis", classeId: "4", photo: "/avatars/96.jpg" },
    { id: "97", nom: "Cordier", prenom: "Louise", classeId: "4", photo: "/avatars/97.jpg" },
    { id: "98", nom: "Pichon", prenom: "Alexandre", classeId: "4", photo: "/avatars/98.jpg" },
    { id: "99", nom: "Lejeune", prenom: "Chloé", classeId: "4", photo: "/avatars/99.jpg" },
    { id: "100", nom: "Bouvier", prenom: "Antoine", classeId: "4", photo: "/avatars/100.jpg" },
    { id: "101", nom: "Martinez", prenom: "Juliette", classeId: "4", photo: "/avatars/101.jpg" },
    { id: "102", nom: "Blanchard", prenom: "Baptiste", classeId: "4", photo: "/avatars/102.jpg" },
    { id: "103", nom: "Collet", prenom: "Léna", classeId: "4", photo: "/avatars/103.jpg" },
    { id: "104", nom: "Lemonnier", prenom: "Raphaël", classeId: "4", photo: "/avatars/104.jpg" },
    { id: "105", nom: "Marie", prenom: "Zoé", classeId: "4", photo: "/avatars/105.jpg" },
    { id: "106", nom: "Dupuy", prenom: "Paul", classeId: "4", photo: "/avatars/106.jpg" },
    { id: "107", nom: "Maillot", prenom: "Lola", classeId: "4", photo: "/avatars/107.jpg" },
    { id: "108", nom: "Delattre", prenom: "Arthur", classeId: "4", photo: "/avatars/108.jpg" },
    { id: "109", nom: "Chauvin", prenom: "Sarah", classeId: "4", photo: "/avatars/109.jpg" },
    { id: "110", nom: "Briand", prenom: "Tom", classeId: "4", photo: "/avatars/110.jpg" },
    { id: "111", nom: "Pasquier", prenom: "Maëlys", classeId: "4", photo: "/avatars/111.jpg" },
    { id: "112", nom: "Guibert", prenom: "Noah", classeId: "4", photo: "/avatars/112.jpg" },
    { id: "113", nom: "Parent", prenom: "Eva", classeId: "4", photo: "/avatars/113.jpg" },
    { id: "114", nom: "Labbe", prenom: "Louis", classeId: "4", photo: "/avatars/114.jpg" },
  
    // 2nde A (32 élèves)
    { id: "12", nom: "Garcia", prenom: "Manon", classeId: "5", photo: "/avatars/12.jpg" },
    { id: "13", nom: "Fournier", prenom: "Maxime", classeId: "5", photo: "/avatars/13.jpg" },
    { id: "115", nom: "Leroux", prenom: "Clara", classeId: "5", photo: "/avatars/115.jpg" },
    { id: "116", nom: "Roussel", prenom: "Enzo", classeId: "5", photo: "/avatars/116.jpg" },
    { id: "117", nom: "Mathieu", prenom: "Inès", classeId: "5", photo: "/avatars/117.jpg" },
    { id: "118", nom: "Serra", prenom: "Mathis", classeId: "5", photo: "/avatars/118.jpg" },
    { id: "119", nom: "Deschamps", prenom: "Louise", classeId: "5", photo: "/avatars/119.jpg" },
    { id: "120", nom: "Samson", prenom: "Alexandre", classeId: "5", photo: "/avatars/120.jpg" },
    { id: "121", nom: "Marchal", prenom: "Chloé", classeId: "5", photo: "/avatars/121.jpg" },
    { id: "122", nom: "Maillet", prenom: "Antoine", classeId: "5", photo: "/avatars/122.jpg" },
    { id: "123", nom: "Boutin", prenom: "Juliette", classeId: "5", photo: "/avatars/123.jpg" },
    { id: "124", nom: "Bigot", prenom: "Baptiste", classeId: "5", photo: "/avatars/124.jpg" },
    { id: "125", nom: "Tessier", prenom: "Léna", classeId: "5", photo: "/avatars/125.jpg" },
    { id: "126", nom: "Morin", prenom: "Raphaël", classeId: "5", photo: "/avatars/126.jpg" },
    { id: "127", nom: "Dijoux", prenom: "Zoé", classeId: "5", photo: "/avatars/127.jpg" },
    { id: "128", nom: "Chauveau", prenom: "Paul", classeId: "5", photo: "/avatars/128.jpg" },
    { id: "129", nom: "Boulay", prenom: "Lola", classeId: "5", photo: "/avatars/129.jpg" },
    { id: "130", nom: "Regnier", prenom: "Arthur", classeId: "5", photo: "/avatars/130.jpg" },
    { id: "131", nom: "Guichard", prenom: "Sarah", classeId: "5", photo: "/avatars/131.jpg" },
    { id: "132", nom: "Blin", prenom: "Tom", classeId: "5", photo: "/avatars/132.jpg" },
    { id: "133", nom: "Pineau", prenom: "Maëlys", classeId: "5", photo: "/avatars/133.jpg" },
    { id: "134", nom: "Baudry", prenom: "Noah", classeId: "5", photo: "/avatars/134.jpg" },
    { id: "135", nom: "Allard", prenom: "Eva", classeId: "5", photo: "/avatars/135.jpg" },
    { id: "136", nom: "Lefort", prenom: "Louis", classeId: "5", photo: "/avatars/136.jpg" },
    { id: "137", nom: "Chartier", prenom: "Jade", classeId: "5", photo: "/avatars/137.jpg" },
    { id: "138", nom: "Bruneau", prenom: "Gabriel", classeId: "5", photo: "/avatars/138.jpg" },
    { id: "139", nom: "Mace", prenom: "Lilou", classeId: "5", photo: "/avatars/139.jpg" },
    { id: "140", nom: "Hardy", prenom: "Timéo", classeId: "5", photo: "/avatars/140.jpg" },
    { id: "141", nom: "Laine", prenom: "Romane", classeId: "5", photo: "/avatars/141.jpg" },
    { id: "142", nom: "Gosselin", prenom: "Nolan", classeId: "5", photo: "/avatars/142.jpg" },
    { id: "143", nom: "Bouchet", prenom: "Ambre", classeId: "5", photo: "/avatars/143.jpg" },
    { id: "144", nom: "Tanguy", prenom: "Sacha", classeId: "5", photo: "/avatars/144.jpg" },
  
    // 1ère B (30 élèves)
    { id: "14", nom: "Lopez", prenom: "Inès", classeId: "6", photo: "/avatars/14.jpg" },
    { id: "15", nom: "Sanchez", prenom: "Enzo", classeId: "6", photo: "/avatars/15.jpg" },
    { id: "145", nom: "Bouquet", prenom: "Mathis", classeId: "6", photo: "/avatars/145.jpg" },
    { id: "146", nom: "Toussaint", prenom: "Louise", classeId: "6", photo: "/avatars/146.jpg" },
    { id: "147", nom: "Laporte", prenom: "Alexandre", classeId: "6", photo: "/avatars/147.jpg" },
    { id: "148", nom: "Delorme", prenom: "Chloé", classeId: "6", photo: "/avatars/148.jpg" },
    { id: "149", nom: "Launay", prenom: "Antoine", classeId: "6", photo: "/avatars/149.jpg" },
    { id: "150", nom: "Pottier", prenom: "Juliette", classeId: "6", photo: "/avatars/150.jpg" },
    { id: "151", nom: "Bonnin", prenom: "Baptiste", classeId: "6", photo: "/avatars/151.jpg" },
    { id: "152", nom: "Foucher", prenom: "Léna", classeId: "6", photo: "/avatars/152.jpg" },
    { id: "153", nom: "Neveu", prenom: "Raphaël", classeId: "6", photo: "/avatars/153.jpg" },
    { id: "154", nom: "Seznec", prenom: "Zoé", classeId: "6", photo: "/avatars/154.jpg" },
    { id: "155", nom: "Lefevre", prenom: "Paul", classeId: "6", photo: "/avatars/155.jpg" },
    { id: "156", nom: "Bodin", prenom: "Lola", classeId: "6", photo: "/avatars/156.jpg" },
    { id: "157", nom: "Guillon", prenom: "Arthur", classeId: "6", photo: "/avatars/157.jpg" },
    { id: "158", nom: "Leconte", prenom: "Sarah", classeId: "6", photo: "/avatars/158.jpg" },
    { id: "159", nom: "Besson", prenom: "Tom", classeId: "6", photo: "/avatars/159.jpg" },
    { id: "160", nom: "Bouvet", prenom: "Maëlys", classeId: "6", photo: "/avatars/160.jpg" },
    { id: "161", nom: "Hamon", prenom: "Noah", classeId: "6", photo: "/avatars/161.jpg" },
    { id: "162", nom: "Le Gall", prenom: "Eva", classeId: "6", photo: "/avatars/162.jpg" },
    { id: "163", nom: "Salmon", prenom: "Louis", classeId: "6", photo: "/avatars/163.jpg" },
    { id: "164", nom: "Girault", prenom: "Jade", classeId: "6", photo: "/avatars/164.jpg" },
    { id: "165", nom: "Pacaud", prenom: "Gabriel", classeId: "6", photo: "/avatars/165.jpg" },
    { id: "166", nom: "Voisin", prenom: "Lilou", classeId: "6", photo: "/avatars/166.jpg" },
    { id: "167", nom: "Lelievre", prenom: "Timéo", classeId: "6", photo: "/avatars/167.jpg" },
    { id: "168", nom: "Riou", prenom: "Romane", classeId: "6", photo: "/avatars/168.jpg" },
    { id: "169", nom: "Baudoin", prenom: "Nolan", classeId: "6", photo: "/avatars/169.jpg" },
    { id: "170", nom: "Chabert", prenom: "Ambre", classeId: "6", photo: "/avatars/170.jpg" },
    { id: "171", nom: "Marechal", prenom: "Sacha", classeId: "6", photo: "/avatars/171.jpg" },
    { id: "172", nom: "Humbert", prenom: "Anna", classeId: "6", photo: "/avatars/172.jpg" },
  
    // Terminale C (28 élèves)
    { id: "16", nom: "Perez", prenom: "Léa", classeId: "7", photo: "/avatars/16.jpg" },
    { id: "17", nom: "Gomez", prenom: "Mathis", classeId: "7", photo: "/avatars/17.jpg" },
    { id: "173", nom: "Baudin", prenom: "Louise", classeId: "7", photo: "/avatars/173.jpg" },
    { id: "174", nom: "Guillou", prenom: "Alexandre", classeId: "7", photo: "/avatars/174.jpg" },
    { id: "175", nom: "Grondin", prenom: "Chloé", classeId: "7", photo: "/avatars/175.jpg" },
    { id: "176", nom: "Brossard", prenom: "Antoine", classeId: "7", photo: "/avatars/176.jpg" },
    { id: "177", nom: "Pereira", prenom: "Juliette", classeId: "7", photo: "/avatars/177.jpg" },
    { id: "178", nom: "Texier", prenom: "Baptiste", classeId: "7", photo: "/avatars/178.jpg" },
    { id: "179", nom: "Lesage", prenom: "Léna", classeId: "7", photo: "/avatars/179.jpg" },
    { id: "180", nom: "Laborde", prenom: "Raphaël", classeId: "7", photo: "/avatars/180.jpg" },
    { id: "181", nom: "Delahaye", prenom: "Zoé", classeId: "7", photo: "/avatars/181.jpg" },
    { id: "182", nom: "Pruvost", prenom: "Paul", classeId: "7", photo: "/avatars/182.jpg" },
    { id: "183", nom: "Bouillon", prenom: "Lola", classeId: "7", photo: "/avatars/183.jpg" },
    { id: "184", nom: "Ruffin", prenom: "Arthur", classeId: "7", photo: "/avatars/184.jpg" },
    { id: "185", nom: "Michaud", prenom: "Sarah", classeId: "7", photo: "/avatars/185.jpg" },
    { id: "186", nom: "Verdier", prenom: "Tom", classeId: "7", photo: "/avatars/186.jpg" },
    { id: "187", nom: "Boulanger", prenom: "Maëlys", classeId: "7", photo: "/avatars/187.jpg" },
    { id: "188", nom: "Roland", prenom: "Noah", classeId: "7", photo: "/avatars/188.jpg" },
    { id: "189", nom: "Joly", prenom: "Eva", classeId: "7", photo: "/avatars/189.jpg" },
    { id: "190", nom: "Weber", prenom: "Louis", classeId: "7", photo: "/avatars/190.jpg" },
    { id: "191", nom: "Pages", prenom: "Jade", classeId: "7", photo: "/avatars/191.jpg" },
    { id: "192", nom: "Jacob", prenom: "Gabriel", classeId: "7", photo: "/avatars/192.jpg" },
    { id: "193", nom: "Lombard", prenom: "Lilou", classeId: "7", photo: "/avatars/193.jpg" },
    { id: "194", nom: "Royer", prenom: "Timéo", classeId: "7", photo: "/avatars/194.jpg" },
    { id: "195", nom: "Albert", prenom: "Romane", classeId: "7", photo: "/avatars/195.jpg" },
    { id: "196", nom: "Vallee", prenom: "Nolan", classeId: "7", photo: "/avatars/196.jpg" },
    { id: "197", nom: "Peltier", prenom: "Ambre", classeId: "7", photo: "/avatars/197.jpg" },
    { id: "198", nom: "Camus", prenom: "Sacha", classeId: "7", photo: "/avatars/198.jpg" }
  ];

  export const cours: Cours[] = [
    // 6ème A (24 élèves)
    { id: "1", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "09:00", classeId: "1", salle: "B101", professeur: "M. Koné" },
    { id: "2", nom: "Français", jour: "Lundi", heureDebut: "09:00", heureFin: "10:00", classeId: "1", salle: "B102", professeur: "Mme. Diabaté" },
    { id: "3", nom: "Histoire-Géographie", jour: "Lundi", heureDebut: "10:30", heureFin: "11:30", classeId: "1", salle: "B103", professeur: "M. Kouamé" },
    { id: "4", nom: "SVT", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "1", salle: "Labo A", professeur: "Mme. Traoré" },
    { id: "5", nom: "Anglais", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "1", salle: "B104", professeur: "M. Soro" },
    { id: "6", nom: "EPS", jour: "Mardi", heureDebut: "14:00", heureFin: "16:00", classeId: "1", salle: "Stade", professeur: "M. Bamba" },
    { id: "7", nom: "Education Civique", jour: "Mercredi", heureDebut: "08:00", heureFin: "09:00", classeId: "1", salle: "B105", professeur: "Mme. Kouadio" },
    { id: "8", nom: "Physique-Chimie", jour: "Jeudi", heureDebut: "10:00", heureFin: "11:00", classeId: "1", salle: "Labo B", professeur: "M. Coulibaly" },
    { id: "9", nom: "Technologie", jour: "Vendredi", heureDebut: "09:00", heureFin: "10:00", classeId: "1", salle: "Atelier", professeur: "M. N'Guessan" },
  
    // 5ème B (28 élèves)
    { id: "10", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "09:00", classeId: "2", salle: "B201", professeur: "M. Yéo" },
    { id: "11", nom: "Français", jour: "Lundi", heureDebut: "09:00", heureFin: "10:00", classeId: "2", salle: "B202", professeur: "Mme. Konaté" },
    { id: "12", nom: "Histoire-Géographie", jour: "Lundi", heureDebut: "10:30", heureFin: "11:30", classeId: "2", salle: "B203", professeur: "M. Fofana" },
    { id: "13", nom: "SVT", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "2", salle: "Labo A", professeur: "Mme. Doumbia" },
    { id: "14", nom: "Anglais", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "2", salle: "B204", professeur: "M. Keita" },
    { id: "15", nom: "EPS", jour: "Mercredi", heureDebut: "14:00", heureFin: "16:00", classeId: "2", salle: "Stade", professeur: "M. Diarrassouba" },
    { id: "16", nom: "Physique-Chimie", jour: "Jeudi", heureDebut: "10:00", heureFin: "11:00", classeId: "2", salle: "Labo B", professeur: "M. Sanogo" },
    { id: "17", nom: "Allemand", jour: "Vendredi", heureDebut: "09:00", heureFin: "10:00", classeId: "2", salle: "B205", professeur: "Mme. Kamara" },
  
    // 4ème C (26 élèves)
    { id: "18", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "09:00", classeId: "3", salle: "B301", professeur: "M. Kouassi" },
    { id: "19", nom: "Français", jour: "Lundi", heureDebut: "09:00", heureFin: "10:00", classeId: "3", salle: "B302", professeur: "Mme. Cissé" },
    { id: "20", nom: "Histoire-Géographie", jour: "Lundi", heureDebut: "10:30", heureFin: "11:30", classeId: "3", salle: "B303", professeur: "M. Ouattara" },
    { id: "21", nom: "SVT", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "3", salle: "Labo A", professeur: "Mme. Diallo" },
    { id: "22", nom: "Anglais", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "3", salle: "B304", professeur: "M. Bamba" },
    { id: "23", nom: "Physique-Chimie", jour: "Mercredi", heureDebut: "10:00", heureFin: "11:00", classeId: "3", salle: "Labo B", professeur: "M. Koffi" },
    { id: "24", nom: "Espagnol", jour: "Jeudi", heureDebut: "11:00", heureFin: "12:00", classeId: "3", salle: "B305", professeur: "Mme. Touré" },
    { id: "25", nom: "Informatique", jour: "Vendredi", heureDebut: "09:00", heureFin: "10:00", classeId: "3", salle: "Salle Info", professeur: "M. Aké" },
  
    // 3ème D (30 élèves)
    { id: "26", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "09:00", classeId: "4", salle: "B401", professeur: "M. Adou" },
    { id: "27", nom: "Français", jour: "Lundi", heureDebut: "09:00", heureFin: "10:00", classeId: "4", salle: "B402", professeur: "Mme. Sylla" },
    { id: "28", nom: "Histoire-Géographie", jour: "Lundi", heureDebut: "10:30", heureFin: "11:30", classeId: "4", salle: "B403", professeur: "M. Gbamé" },
    { id: "29", nom: "SVT", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "4", salle: "Labo A", professeur: "Mme. Bakayoko" },
    { id: "30", nom: "Anglais", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "4", salle: "B404", professeur: "M. Coulibaly" },
    { id: "31", nom: "Physique-Chimie", jour: "Mercredi", heureDebut: "10:00", heureFin: "11:00", classeId: "4", salle: "Labo B", professeur: "M. Konaté" },
    { id: "32", nom: "Philosophie", jour: "Jeudi", heureDebut: "11:00", heureFin: "12:00", classeId: "4", salle: "B405", professeur: "Mme. Diomandé" },
    { id: "33", nom: "Education aux Droits Humains", jour: "Vendredi", heureDebut: "09:00", heureFin: "10:00", classeId: "4", salle: "B406", professeur: "M. Sissoko" },
  
    // 2nde A (32 élèves)
    { id: "34", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "10:00", classeId: "5", salle: "B501", professeur: "M. N'Dri" },
    { id: "35", nom: "Français", jour: "Lundi", heureDebut: "10:15", heureFin: "11:15", classeId: "5", salle: "B502", professeur: "Mme. Kéita" },
    { id: "36", nom: "Histoire", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "5", salle: "B503", professeur: "M. Bédié" },
    { id: "37", nom: "Géographie", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "5", salle: "B503", professeur: "M. Gbagbo" },
    { id: "38", nom: "SVT", jour: "Mercredi", heureDebut: "08:00", heureFin: "10:00", classeId: "5", salle: "Labo A", professeur: "Mme. Ouédraogo" },
    { id: "39", nom: "Physique-Chimie", jour: "Jeudi", heureDebut: "08:00", heureFin: "10:00", classeId: "5", salle: "Labo B", professeur: "M. Sangaré" },
    { id: "40", nom: "Philosophie", jour: "Vendredi", heureDebut: "09:00", heureFin: "10:00", classeId: "5", salle: "B504", professeur: "Mme. Bamba" },
    { id: "41", nom: "Langues Vivantes (Anglais)", jour: "Vendredi", heureDebut: "10:15", heureFin: "11:15", classeId: "5", salle: "B505", professeur: "M. Traoré" },
    { id: "42", nom: "EPS", jour: "Mercredi", heureDebut: "14:00", heureFin: "16:00", classeId: "5", salle: "Stade", professeur: "M. Zadi" },
  
    // 1ère B (30 élèves)
    { id: "43", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "10:00", classeId: "6", salle: "B601", professeur: "M. Kipré" },
    { id: "44", nom: "Français", jour: "Lundi", heureDebut: "10:15", heureFin: "11:15", classeId: "6", salle: "B602", professeur: "Mme. Gnahoré" },
    { id: "45", nom: "Histoire", jour: "Mardi", heureDebut: "08:00", heureFin: "09:00", classeId: "6", salle: "B603", professeur: "M. Bamba" },
    { id: "46", nom: "Géographie", jour: "Mardi", heureDebut: "09:00", heureFin: "10:00", classeId: "6", salle: "B603", professeur: "M. Koné" },
    { id: "47", nom: "SVT", jour: "Mercredi", heureDebut: "08:00", heureFin: "10:00", classeId: "6", salle: "Labo A", professeur: "Mme. Diakité" },
    { id: "48", nom: "Physique-Chimie", jour: "Jeudi", heureDebut: "08:00", heureFin: "10:00", classeId: "6", salle: "Labo B", professeur: "M. Kouamé" },
    { id: "49", nom: "Philosophie", jour: "Vendredi", heureDebut: "09:00", heureFin: "11:00", classeId: "6", salle: "B604", professeur: "M. Yapo" },
    { id: "50", nom: "Anglais", jour: "Vendredi", heureDebut: "11:15", heureFin: "12:15", classeId: "6", salle: "B605", professeur: "Mme. Coulibaly" },
    { id: "51", nom: "Espagnol", jour: "Jeudi", heureDebut: "14:00", heureFin: "15:00", classeId: "6", salle: "B606", professeur: "Mme. N'Guessan" },
  
    // Terminale C (28 élèves)
    { id: "52", nom: "Mathématiques", jour: "Lundi", heureDebut: "08:00", heureFin: "10:00", classeId: "7", salle: "B701", professeur: "M. Fadiga" },
    { id: "53", nom: "Philosophie", jour: "Lundi", heureDebut: "10:15", heureFin: "12:15", classeId: "7", salle: "B702", professeur: "M. Gbonkan" },
    { id: "54", nom: "SVT", jour: "Mardi", heureDebut: "08:00", heureFin: "10:00", classeId: "7", salle: "Labo A", professeur: "Mme. Koné" },
    { id: "55", nom: "Physique-Chimie", jour: "Mercredi", heureDebut: "08:00", heureFin: "10:00", classeId: "7", salle: "Labo B", professeur: "M. Diabaté" },
    { id: "56", nom: "Français", jour: "Jeudi", heureDebut: "08:00", heureFin: "09:00", classeId: "7", salle: "B703", professeur: "Mme. Touré" },
    { id: "57", nom: "Histoire", jour: "Jeudi", heureDebut: "09:00", heureFin: "10:00", classeId: "7", salle: "B704", professeur: "M. Koulibaly" },
    { id: "58", nom: "Géographie", jour: "Jeudi", heureDebut: "10:15", heureFin: "11:15", classeId: "7", salle: "B704", professeur: "M. Bamba" },
    { id: "59", nom: "Anglais", jour: "Vendredi", heureDebut: "08:00", heureFin: "09:00", classeId: "7", salle: "B705", professeur: "M. Soro" },
    { id: "60", nom: "Education Civique", jour: "Vendredi", heureDebut: "09:15", heureFin: "10:15", classeId: "7", salle: "B706", professeur: "Mme. Doumbia" }
  ];

export const jours = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];